### PR TITLE
Added feature to format the current statement (without having to select it first).

### PR DESCRIPTION
**Pull request by yixiang**
Resubmitting a previously closed pull request #102 with updated comments.

### CODE REVIEW

**Comment by travisjeffery** [comment]
ok i'll take a look soon and see how useful this is

**Comment by yixiang** [comment]
Any updates?

**Comment by yixiang** [comment]
Any updates, Travis? I think this is a really useful feature. Simple but very useful. It provides the ability to format a line without selecting it first.

**Comment by yixiang** [comment]
Trying another approach with #121

**Pull request closed without merging**
